// frontend/microfrontends/administration/src/components/SiteAdminViews.tsx - Sub-views for other tabs
import React from 'react';
import {
  BookOpen,
  Upload,
  Download,
  ScrollText,
  Shield,
  Settings,
  FileSpreadsheet,
  CheckCircle2,
  Clock,
  Lock,
  Globe,
  Bell,
} from 'lucide-react';
import { ExportSubOption } from '../types/admin';

// ---------------------------------------------------------------------------
// Studies View
// ---------------------------------------------------------------------------
export const StudiesView: React.FC = () => {
  return (
    <div className="site-admin-card-view">
      <div className="site-admin-card-view-header">
        <div>
          <h2 className="site-admin-card-view-title">Site Studies Management</h2>
          <p className="site-admin-card-view-subtitle">
            Configure active clinical trials, protocol allocations, and coordinator assignments.
          </p>
        </div>
        <button type="button" className="btn btn-primary">
          <BookOpen size={16} aria-hidden="true" />
          <span>New Study Setup</span>
        </button>
      </div>

      <div className="site-admin-info-grid">
        <div className="site-admin-info-tile">
          <h4>Active Clinical Studies</h4>
          <p>8 studies actively enrolling participants with open IRB approvals.</p>
        </div>
        <div className="site-admin-info-tile">
          <h4>Archived & Closed</h4>
          <p>4 studies completed and preserved in read-only audit compliance.</p>
        </div>
        <div className="site-admin-info-tile">
          <h4>Multi-Site Affiliations</h4>
          <p>Connected across 3 regional medical center campuses.</p>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Import View
// ---------------------------------------------------------------------------
export const ImportView: React.FC = () => {
  return (
    <div className="site-admin-card-view">
      <div className="site-admin-card-view-header">
        <div>
          <h2 className="site-admin-card-view-title">Data Intake & Import</h2>
          <p className="site-admin-card-view-subtitle">
            Bulk import user credentials, participant registries, or protocol datasets via CSV or Excel.
          </p>
        </div>
      </div>

      <div className="site-admin-info-grid">
        <div className="site-admin-info-tile">
          <Upload size={24} className="text-blue-600 mb-1" />
          <h4>Users & Credentials Import</h4>
          <p>Upload a standard CSV template to batch provision new site team accounts.</p>
          <button type="button" className="btn btn-secondary btn-sm mt-2">
            Download CSV Template
          </button>
        </div>
        <div className="site-admin-info-tile">
          <FileSpreadsheet size={24} className="text-cyan-600 mb-1" />
          <h4>Registry Records Import</h4>
          <p>Import screening logs and registry participants mapped to protocol IDs.</p>
          <button type="button" className="btn btn-secondary btn-sm mt-2">
            Upload Registry File
          </button>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Export View
// ---------------------------------------------------------------------------
export interface ExportViewProps {
  selectedSubOption?: ExportSubOption;
}

export const ExportView: React.FC<ExportViewProps> = ({ selectedSubOption = 'new_config' }) => {
  return (
    <div className="site-admin-card-view">
      <div className="site-admin-card-view-header">
        <div>
          <h2 className="site-admin-card-view-title">Export Configurations & Artifacts</h2>
          <p className="site-admin-card-view-subtitle">
            Configure scheduled exports, view personal report downloads, and access shared data packages.
          </p>
        </div>
      </div>

      <div className="site-admin-info-grid">
        <div className="site-admin-info-tile">
          <h4>New Export Config</h4>
          <p>Set custom column filters, date scopes, and PHI de-identification rules.</p>
          <button type="button" className="btn btn-primary btn-sm mt-2">
            Create Configuration
          </button>
        </div>

        <div className="site-admin-info-tile">
          <h4>My Exports</h4>
          <p>Recent export packages generated by your administrator session.</p>
          <span className="text-xs text-gray-500">3 archives ready for download</span>
        </div>

        <div className="site-admin-info-tile">
          <h4>Shared With Me</h4>
          <p>Compliance and registry datasets published by study principal investigators.</p>
          <span className="text-xs text-gray-500">2 shared data packages</span>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Audit Log View
// ---------------------------------------------------------------------------
export const AuditLogView: React.FC = () => {
  return (
    <div className="site-admin-card-view">
      <div className="site-admin-card-view-header">
        <div>
          <h2 className="site-admin-card-view-title">System & Security Audit Ledger</h2>
          <p className="site-admin-card-view-subtitle">
            Tamper-evident logs of administrative access, user role modifications, and authentication events.
          </p>
        </div>
        <button type="button" className="btn btn-secondary">
          <Download size={15} aria-hidden="true" />
          <span>Export Ledger</span>
        </button>
      </div>

      <div className="site-admin-info-grid">
        <div className="site-admin-info-tile">
          <div className="flex items-center gap-2">
            <CheckCircle2 size={16} className="text-emerald-600" />
            <h4>User Permissions Modified</h4>
          </div>
          <p>Role 'Site Admin' updated for Sriram Chavali by SuperAdmin.</p>
          <span className="text-xs text-gray-400">Today at 10:45 AM</span>
        </div>

        <div className="site-admin-info-tile">
          <div className="flex items-center gap-2">
            <Clock size={16} className="text-blue-600" />
            <h4>Successful Authentication</h4>
          </div>
          <p>Multi-factor verification approved for Christi Matthews.</p>
          <span className="text-xs text-gray-400">Today at 09:12 AM</span>
        </div>

        <div className="site-admin-info-tile">
          <div className="flex items-center gap-2">
            <Shield size={16} className="text-amber-600" />
            <h4>Password Policy Enforced</h4>
          </div>
          <p>Mandatory 90-day password reset scheduled for 6 coordinator accounts.</p>
          <span className="text-xs text-gray-400">Yesterday at 04:30 PM</span>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Security View
// ---------------------------------------------------------------------------
export const SecurityView: React.FC = () => {
  return (
    <div className="site-admin-card-view">
      <div className="site-admin-card-view-header">
        <div>
          <h2 className="site-admin-card-view-title">Security & Access Policies</h2>
          <p className="site-admin-card-view-subtitle">
            Configure HIPAA compliant session policies, 2FA requirements, and role-based access rules.
          </p>
        </div>
      </div>

      <div className="site-admin-info-grid">
        <div className="site-admin-info-tile">
          <Lock size={20} className="text-blue-600 mb-1" />
          <h4>Multi-Factor Authentication (2FA)</h4>
          <p>Mandatory for all Site Admin and Clinical Coordinator roles.</p>
          <span className="badge badge-success mt-1">Enforced</span>
        </div>

        <div className="site-admin-info-tile">
          <Clock size={20} className="text-amber-600 mb-1" />
          <h4>Session Timeout</h4>
          <p>Automatic logout after 15 minutes of user inactivity.</p>
          <span className="badge badge-info mt-1">15 Minutes</span>
        </div>

        <div className="site-admin-info-tile">
          <Shield size={20} className="text-emerald-600 mb-1" />
          <h4>Password Complexity</h4>
          <p>Minimum 12 characters, including uppercase, lowercase, numbers, and symbols.</p>
          <span className="badge badge-success mt-1">Strict</span>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// General Settings View
// ---------------------------------------------------------------------------
export const GeneralSettingsView: React.FC = () => {
  return (
    <div className="site-admin-card-view">
      <div className="site-admin-card-view-header">
        <div>
          <h2 className="site-admin-card-view-title">General Site Settings</h2>
          <p className="site-admin-card-view-subtitle">
            Configure site metadata, facility addresses, notifications, and primary points of contact.
          </p>
        </div>
      </div>

      <div className="site-admin-info-grid">
        <div className="site-admin-info-tile">
          <Globe size={20} className="text-blue-600 mb-1" />
          <h4>Facility Details</h4>
          <p>EnrollNow Clinical Research Center • Facility Code: SITE-001</p>
          <span className="text-xs text-gray-500">Timezone: America/New_York (EST)</span>
        </div>

        <div className="site-admin-info-tile">
          <Bell size={20} className="text-cyan-600 mb-1" />
          <h4>System Notifications</h4>
          <p>Email alerts on study enrollment milestones and protocol intake approvals.</p>
          <span className="badge badge-success mt-1">Active</span>
        </div>

        <div className="site-admin-info-tile">
          <Settings size={20} className="text-purple-600 mb-1" />
          <h4>System Maintenance</h4>
          <p>Scheduled maintenance window: Sundays 02:00 AM - 04:00 AM EST.</p>
          <span className="badge badge-neutral mt-1">Standard</span>
        </div>
      </div>
    </div>
  );
};
