<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.enrollnow</groupId>
		<artifactId>enrollnow-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>enrollnow-app</artifactId>
	<packaging>jar</packaging>

	<name>EnrollNow Main Application</name>

	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-common</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-identity-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-survey-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-study-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-participant-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-recruitment-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-task-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-communication-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.enrollnow</groupId>
			<artifactId>enrollnow-document-service</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>
	</dependencies>

</project>