spring.application.name=enrollnow-app

spring.datasource.url=jdbc:postgresql://localhost:5432/enrollnowdb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false