// frontend/microfrontends/administration/src/mockData.ts - Site Admin Mock Data
import { SiteAdminUser } from './types/admin';

export const INITIAL_SITE_USERS: SiteAdminUser[] = [
  {
    id: 'usr-001',
    name: 'Sriram Chavali',
    email: 'sriram.chavali@solventek.com',
    sitePermissions: 'Site Admin',
    studies: [
      'AD MCIData',
      'Ana Study',
      'Amit Sample',
      'Ana Sample ss',
      'ana diwedi',
      'Self Scheduling',
    ],
    status: 'Active',
    title: 'Lead System Administrator',
    createdAt: '2026-01-10',
  },
  {
    id: 'usr-002',
    name: 'Bhagyashree Das',
    email: 'bhagyashree.das@solventek.com',
    sitePermissions: 'Site Admin',
    studies: [
      'AD MCIData',
      'Amit Sample',
      'siri',
      'testwithbhagya',
      'S37 Test',
      'SAMPLE STUDY',
    ],
    status: 'Active',
    title: 'Principal Operations Manager',
    createdAt: '2026-01-15',
  },
  {
    id: 'usr-003',
    name: 'Ana Diwedi',
    email: 'ana.diwedi@solventek.com',
    sitePermissions: 'Site Admin',
    studies: [
      'AD MCIData',
      'Ana Study',
      'Amit Sample',
      'Ana Sample ss',
      'ana diwedi',
      'Self Scheduling',
    ],
    status: 'Active',
    title: 'Clinical Research Coordinator',
    createdAt: '2026-02-01',
  },
  {
    id: 'usr-004',
    name: 'Suneel Kumar',
    email: 'suneel.kumar@solventek.com',
    sitePermissions: 'Site Admin',
    studies: [
      'AD MCIData',
      'Amit Sample',
      'MyTest',
      'Self Scheduling',
    ],
    status: 'Active',
    title: 'Site Technical Lead',
    createdAt: '2026-02-14',
  },
  {
    id: 'usr-005',
    name: 'Vidya Maned',
    email: 'vidya.maned@solventek.com',
    sitePermissions: 'Site Admin',
    studies: [
      'AD MCIData',
      'Amit Sample',
      'SAMPLE STUDY',
      'Self Scheduling',
    ],
    status: 'Active',
    title: 'Senior Clinical Specialist',
    createdAt: '2026-02-20',
  },
  {
    id: 'usr-006',
    name: 'Christi Matthews',
    email: 'christi@ripplescience.com',
    sitePermissions: 'Site Admin',
    studies: [
      'Self Scheduling',
      'ADRC Comm Hour',
      'ECHO',
      'Autism Study',
      'Customer Succes',
      'Sleep Study',
      'Longitud Study',
      'Coffee Hour',
      'Survey Creator',
      'New Study',
      'BLINDING DATA',
    ],
    status: 'Active',
    title: 'Senior Site Administrator',
    createdAt: '2025-11-05',
  },
  {
    id: 'usr-007',
    name: 'Marcus Vance',
    email: 'marcus.vance@solventek.com',
    sitePermissions: 'Study Coordinator',
    studies: [
      'AD MCIData',
      'ECHO',
      'Autism Study',
    ],
    status: 'Active',
    title: 'Clinical Coordinator',
    createdAt: '2026-03-01',
  },
  {
    id: 'usr-008',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@solventek.com',
    sitePermissions: 'Investigator',
    studies: [
      'Sleep Study',
      'Longitud Study',
    ],
    status: 'Inactive',
    title: 'Principal Investigator',
    createdAt: '2025-09-12',
  },
];

export const AVAILABLE_STUDIES_LIST: string[] = [
  'AD MCIData',
  'ADRC Comm Hour',
  'Amit Sample',
  'ana diwedi',
  'Ana Sample ss',
  'Ana Study',
  'Autism Study',
  'NO CV',
  'S37 Test',
  'SAMPLE STUDY',
  'Self Scheduling',
  'siri',
  'Sleep Study',
  'Survey Creator',
  'Team Games',
  'Test10-7',
  'testwithbhagya',
  'Unblinded RCT',
  'Year End 2022',
  'Year End 2023',
];

export const SITE_PERMISSION_ROLES: string[] = [
  'None',
  'Registry Access Only',
  'Site Manager & Registry Access',
  'Site Admin & Registry Access',
];
