// frontend/microfrontends/participant/src/mockData.ts - Mock Dataset & Options for Participant MFE
import { ParticipantRecord, FilterFieldOption } from './types/participant';

export const initialParticipants: ParticipantRecord[] = [
  {
    id: '1',
    name: 'Drexel University AJDAI',
    firstName: 'Drexel',
    lastName: 'University AJDAI',
    studies: [
      { name: 'ADRC Comm Hour', isLink: true },
      { name: 'Autism Study', isLink: true },
      { name: 'Customer Succes', isLink: false },
      { name: 'AZ Study', isLink: false },
      { name: 'BLINDING DATA', isLink: true },
    ],
    gender: '...',
    age: '...',
    ageNumeric: 36,
    lastContact: '24/09/2026, 08:36 pm',
    status: 'Active',
    city: 'Philadelphia',
    state: 'PA',
    zipcode: '19104',
    phone: '+1 (215) 895-2000',
    familyId: 'FAM-84920',
    dateCreated: '16/06/2026, 08:22 pm',
    globalId: 'AJDAI',
    timezone: 'America/New_York (EDT)',
    tags: ['Genomics Study', 'Cohort Alpha', 'High Priority'],
    contactForFutureStudies: true,
    availableToAddStudy: true,
    globalDateOfLastContact: '09/24/2026 08:36 PM',
    birthMonth: 'March',
    contactMethods: {
      primaryEmail: 'ajdai.registry@drexel.edu',
      secondaryEmail: 'coordinator@drexel-genomics.org',
      phone: '+1 (215) 895-2000',
      address: '3141 Chestnut St, Philadelphia, PA 19104',
      preferredMethod: 'Email',
    },
    demographics: {
      dob: '03/15/1990',
      gender: 'Male',
      ethnicity: 'Not Hispanic or Latino',
      race: 'White / Caucasian',
      primaryLanguage: 'English',
    },
    family: {
      familyRole: 'Proband',
      membersCount: 4,
      pedigreeTreeId: 'PED-9012',
      guardianName: 'N/A (Adult)',
    },
    variables: [
      { name: 'Consent Signed', value: 'Yes (v2.4)', lastUpdated: '06/16/2026' },
      { name: 'Phenotype Category', value: 'Neurodevelopmental', lastUpdated: '07/01/2026' },
      { name: 'Specimen Biobank ID', value: 'BIO-DREXEL-0012', lastUpdated: '08/10/2026' },
      { name: 'Blood Group', value: 'O Positive', lastUpdated: '06/16/2026' },
    ]
  },
  {
    id: '2',
    name: 'Yihenew Abetu',
    firstName: 'Yihenew',
    lastName: 'Abetu',
    studies: [
      { name: 'ADRC Comm Hour', isLink: true },
      { name: 'Autism Study', isLink: true },
    ],
    gender: '...',
    age: '...',
    ageNumeric: 41,
    lastContact: '...',
    status: 'Enrolled',
    city: 'Philadelphia',
    state: 'PA',
    zipcode: '19104',
    phone: '+1 (215) 555-0143',
    familyId: 'FAM-39102',
    dateCreated: '12/04/2026, 11:14 am',
    globalId: 'YABETU',
    timezone: 'America/New_York (EDT)',
    tags: ['Biomarker Study', 'Active Enrollment'],
    contactForFutureStudies: false,
    availableToAddStudy: true,
    globalDateOfLastContact: '09/10/2026 03:20 PM',
    birthMonth: 'July',
    contactMethods: {
      primaryEmail: 'yihenew.abetu@example.org',
      phone: '+1 (215) 555-0143',
      address: '240 S 40th St, Philadelphia, PA 19104',
      preferredMethod: 'Phone',
    },
    demographics: {
      dob: '07/22/1985',
      gender: 'Male',
      ethnicity: 'Not Hispanic or Latino',
      race: 'Black or African American',
      primaryLanguage: 'Amharic, English',
    },
    family: {
      familyRole: 'Proband',
      membersCount: 2,
      pedigreeTreeId: 'PED-3910',
      guardianName: 'N/A',
    },
    variables: [
      { name: 'Consent Signed', value: 'Yes (v2.4)', lastUpdated: '04/12/2026' },
      { name: 'Phenotype Category', value: 'Immunological', lastUpdated: '05/02/2026' },
    ]
  },
  {
    id: '3',
    name: 'Alli Adams',
    firstName: 'Alli',
    lastName: 'Adams',
    studies: [
      { name: 'ADRC Comm Hour', isLink: true },
      { name: 'Customer Survey', isLink: false },
      { name: 'S37 Test', isLink: false },
    ],
    gender: '...',
    age: '...',
    ageNumeric: 13,
    lastContact: '07/02/2025, 04:00 am',
    status: 'Screening',
    city: 'Chicago',
    state: 'IL',
    zipcode: '60603',
    phone: '+1 (312) 555-0199',
    familyId: 'FAM-55421',
    dateCreated: '03/02/2026, 09:45 am',
    globalId: 'AADAMS',
    timezone: 'America/Chicago (CDT)',
    tags: ['Pediatric', 'Longitudinal Survey'],
    contactForFutureStudies: true,
    availableToAddStudy: false,
    globalDateOfLastContact: '08/18/2026 01:15 PM',
    birthMonth: 'November',
    contactMethods: {
      primaryEmail: 'alli.adams@familymail.com',
      phone: '+1 (312) 555-0199',
      address: '104 Michigan Ave, Chicago, IL 60603',
      preferredMethod: 'Email',
    },
    demographics: {
      dob: '11/08/2012',
      gender: 'Female',
      ethnicity: 'Not Hispanic or Latino',
      race: 'White / Caucasian',
      primaryLanguage: 'English',
    },
    family: {
      familyRole: 'Sibling',
      membersCount: 5,
      pedigreeTreeId: 'PED-5542',
      guardianName: 'Sarah Adams (Mother)',
    },
    variables: [
      { name: 'Consent Signed', value: 'Yes - Parental Consent', lastUpdated: '03/02/2026' },
      { name: 'Phenotype Category', value: 'Control / Unaffected', lastUpdated: '03/02/2026' },
    ]
  },
  {
    id: '4',
    name: 'Jackson Adams',
    firstName: 'Jackson',
    lastName: 'Adams',
    studies: [
      { name: 'Dashboard', isLink: false },
    ],
    gender: 'Male',
    age: '34 years 10 months',
    ageNumeric: 34.8,
    lastContact: '...',
    status: 'Enrolled',
    city: 'Chicago',
    state: 'IL',
    zipcode: '60603',
    phone: '+1 (312) 555-0199',
    familyId: 'FAM-55421',
    dateCreated: '03/02/2026, 10:00 am',
    globalId: 'JADAMS1',
    timezone: 'America/Chicago (CDT)',
    tags: ['Pediatric', 'Cohort Alpha'],
    contactForFutureStudies: true,
    availableToAddStudy: true,
    globalDateOfLastContact: '09/01/2026 10:30 AM',
    birthMonth: 'May',
    contactMethods: {
      primaryEmail: 'sarah.adams@familymail.com',
      phone: '+1 (312) 555-0199',
      address: '104 Michigan Ave, Chicago, IL 60603',
      preferredMethod: 'Email',
    },
    demographics: {
      dob: '05/19/1991',
      gender: 'Male',
      ethnicity: 'Not Hispanic or Latino',
      race: 'White / Caucasian',
      primaryLanguage: 'English',
    },
    family: {
      familyRole: 'Proband',
      membersCount: 5,
      pedigreeTreeId: 'PED-5542',
      guardianName: 'Sarah Adams (Mother)',
    },
    variables: [
      { name: 'Consent Signed', value: 'Yes - Parental Consent', lastUpdated: '03/02/2026' },
      { name: 'Phenotype Category', value: 'Metabolic', lastUpdated: '04/10/2026' },
    ]
  },
  {
    id: '5',
    name: 'Jeneva Adams',
    firstName: 'Jeneva',
    lastName: 'Adams',
    studies: [],
    gender: '...',
    age: '...',
    ageNumeric: 7,
    lastContact: '...',
    status: 'Screening',
    city: 'Chicago',
    state: 'IL',
    zipcode: '60603',
    phone: '+1 (312) 555-0199',
    familyId: 'FAM-55421',
    dateCreated: '03/02/2026, 10:12 am',
    globalId: 'JADAMS2',
    timezone: 'America/Chicago (CDT)',
    tags: ['Pediatric'],
    contactForFutureStudies: false,
    availableToAddStudy: false,
    globalDateOfLastContact: '07/20/2026 11:00 AM',
    birthMonth: 'September',
    contactMethods: {
      primaryEmail: 'sarah.adams@familymail.com',
      phone: '+1 (312) 555-0199',
      address: '104 Michigan Ave, Chicago, IL 60603',
      preferredMethod: 'Email',
    },
    demographics: {
      dob: '09/04/2018',
      gender: 'Female',
      ethnicity: 'Not Hispanic or Latino',
      race: 'White / Caucasian',
      primaryLanguage: 'English',
    },
    family: {
      familyRole: 'Sibling',
      membersCount: 5,
      pedigreeTreeId: 'PED-5542',
      guardianName: 'Sarah Adams (Mother)',
    },
    variables: [
      { name: 'Consent Signed', value: 'Yes - Parental Consent', lastUpdated: '03/02/2026' },
      { name: 'Phenotype Category', value: 'Control / Unaffected', lastUpdated: '03/02/2026' },
    ]
  },
  {
    id: '6',
    name: 'Marcus Vance',
    firstName: 'Marcus',
    lastName: 'Vance',
    studies: [
      { name: 'ADRC Comm Hour', isLink: true },
      { name: 'Cardiology Q2', isLink: false },
    ],
    gender: 'Male',
    age: '47 years 8 months',
    ageNumeric: 47.6,
    lastContact: '18/09/2026, 04:12 pm',
    status: 'Active',
    city: 'Seattle',
    state: 'WA',
    zipcode: '98101',
    phone: '+1 (206) 555-0812',
    familyId: 'FAM-11029',
    dateCreated: '20/01/2026, 02:30 pm',
    globalId: 'MVANCE',
    timezone: 'America/Los_Angeles (PDT)',
    tags: ['Cardiology', 'Cohort Beta'],
    contactForFutureStudies: true,
    availableToAddStudy: true,
    globalDateOfLastContact: '09/18/2026 04:12 PM',
    birthMonth: 'December',
    contactMethods: {
      primaryEmail: 'm.vance@soundhealth.org',
      phone: '+1 (206) 555-0812',
      address: '700 Pike St, Seattle, WA 98101',
      preferredMethod: 'Phone',
    },
    demographics: {
      dob: '12/10/1978',
      gender: 'Male',
      ethnicity: 'Not Hispanic or Latino',
      race: 'Asian',
      primaryLanguage: 'English',
    },
    family: {
      familyRole: 'Proband',
      membersCount: 3,
      pedigreeTreeId: 'PED-1102',
      guardianName: 'N/A',
    },
    variables: [
      { name: 'Consent Signed', value: 'Yes (v2.4)', lastUpdated: '01/20/2026' },
      { name: 'Phenotype Category', value: 'Cardiovascular', lastUpdated: '02/11/2026' },
    ]
  },
  {
    id: '7',
    name: 'Elena Rostova',
    firstName: 'Elena',
    lastName: 'Rostova',
    studies: [
      { name: 'Autism Study', isLink: true },
      { name: 'Rare Variant', isLink: true },
    ],
    gender: 'Female',
    age: '32 years 1 month',
    ageNumeric: 32.1,
    lastContact: '22/09/2026, 09:15 am',
    status: 'Completed',
    city: 'Boston',
    state: 'MA',
    zipcode: '02115',
    phone: '+1 (617) 555-0134',
    familyId: 'FAM-67123',
    dateCreated: '18/05/2026, 04:10 pm',
    globalId: 'EROSTO',
    timezone: 'America/New_York (EDT)',
    tags: ['Neurology', 'Rare Variant'],
    contactForFutureStudies: true,
    availableToAddStudy: true,
    globalDateOfLastContact: '09/22/2026 09:15 AM',
    birthMonth: 'August',
    contactMethods: {
      primaryEmail: 'elena.rostova@medresearch.org',
      phone: '+1 (617) 555-0134',
      address: '75 Francis St, Boston, MA 02115',
      preferredMethod: 'Email',
    },
    demographics: {
      dob: '08/30/1993',
      gender: 'Female',
      ethnicity: 'Not Hispanic or Latino',
      race: 'White / Caucasian',
      primaryLanguage: 'Russian, English',
    },
    family: {
      familyRole: 'Proband',
      membersCount: 1,
      pedigreeTreeId: 'PED-6712',
      guardianName: 'N/A',
    },
    variables: [
      { name: 'Consent Signed', value: 'Yes (v2.4)', lastUpdated: '05/18/2026' },
      { name: 'Phenotype Category', value: 'Neuromuscular', lastUpdated: '06/05/2026' },
    ]
  },
  {
    id: '8',
    name: 'Elena Peterson',
    firstName: 'Elena',
    lastName: 'Peterson',
    studies: [
      { name: 'Dashboard', isLink: false },
    ],
    gender: 'Female',
    age: '34 years 3 months',
    ageNumeric: 34.25,
    lastContact: '...',
    status: 'Active',
    city: 'Boston',
    state: 'MA',
    zipcode: '02115',
    phone: '+1 (617) 555-0899',
    familyId: 'FAM-98123',
    dateCreated: '10/06/2026, 10:00 am',
    globalId: 'EPETER',
    timezone: 'America/New_York (EDT)',
    tags: ['Active Enrollment'],
    contactForFutureStudies: false,
    availableToAddStudy: true,
    globalDateOfLastContact: '10/01/2026 09:00 AM',
    birthMonth: 'June',
    contactMethods: {
      primaryEmail: 'elena.peterson@example.org',
      phone: '+1 (617) 555-0899',
      address: '100 Tremont St, Boston, MA',
      preferredMethod: 'Email',
    },
    demographics: {
      dob: '06/12/1992',
      gender: 'Female',
      ethnicity: 'Not Hispanic or Latino',
      race: 'White / Caucasian',
      primaryLanguage: 'English',
    },
    family: {
      familyRole: 'Proband',
      membersCount: 1,
      pedigreeTreeId: 'PED-9812',
      guardianName: 'N/A',
    },
    variables: []
  },
  {
    id: '9',
    name: 'Test4 Test4',
    firstName: 'Test4',
    lastName: 'Test4',
    studies: [],
    gender: '...',
    age: '34 years 5 months',
    ageNumeric: 34.4,
    lastContact: '...',
    status: 'Screening',
    city: 'Philadelphia',
    state: 'PA',
    zipcode: '19104',
    phone: '+1 (215) 555-0999',
    familyId: 'FAM-77112',
    dateCreated: '10/06/2026, 10:30 am',
    globalId: 'TEST4',
    timezone: 'America/New_York (EDT)',
    tags: [],
    contactForFutureStudies: false,
    availableToAddStudy: true,
    globalDateOfLastContact: '10/02/2026 11:00 AM',
    birthMonth: 'April',
    contactMethods: {
      primaryEmail: 'test4.test4@example.org',
      phone: '+1 (215) 555-0999',
      address: 'Main St, Philadelphia, PA',
      preferredMethod: 'Email',
    },
    demographics: {
      dob: '04/10/1992',
      gender: 'Unspecified',
      ethnicity: 'Not Disclosed',
      race: 'Not Disclosed',
      primaryLanguage: 'English',
    },
    family: {
      familyRole: 'Proband',
      membersCount: 1,
      pedigreeTreeId: 'PED-7711',
      guardianName: 'N/A',
    },
    variables: []
  }
];

export const filterFieldOptions: FilterFieldOption[] = [
  { id: 'age', label: 'Age', placeholder: 'e.g. 1y6m or 18mo or 1.5 or 34', type: 'number' },
  { id: 'gender', label: 'Sex/Gender', placeholder: 'e.g. Male, Female, Other', type: 'select' },
  { id: 'studies', label: 'Studies', placeholder: 'e.g. ADRC Comm Hour, Autism Study', type: 'text' },
  { id: 'tags', label: 'Tags', placeholder: 'e.g. Pediatric, Cohort Alpha', type: 'text' },
  { id: 'ethnicity', label: 'Ethnicity', placeholder: 'e.g. Hispanic, Not Hispanic', type: 'text' },
  { id: 'race', label: 'Race', placeholder: 'e.g. White, Asian, Black', type: 'text' },
  { id: 'city', label: 'City', placeholder: 'e.g. Philadelphia, Chicago', type: 'text' },
  { id: 'state', label: 'State', placeholder: 'e.g. PA, IL, WA', type: 'text' },
  { id: 'zipcode', label: 'Zipcode', placeholder: 'e.g. 19104, 60603', type: 'text' },
  { id: 'phone', label: 'Phone Number', placeholder: 'e.g. 215, 312', type: 'text' },
  { id: 'status', label: 'Participant Status', placeholder: 'e.g. Active, Enrolled, Screening', type: 'text' },
  { id: 'lastContact', label: 'Last Contact', placeholder: 'DD/MM/YYYY or 24/09/2026', type: 'date' },
  { id: 'dateCreated', label: 'Date Created', placeholder: 'DD/MM/YYYY', type: 'date' },
  { id: 'birthMonth', label: 'Birth Month', placeholder: 'e.g. January, March, May', type: 'text' },
  { id: 'firstName', label: 'First Name', placeholder: 'e.g. Drexel, Alli, Jackson', type: 'text' },
  { id: 'lastName', label: 'Last Name', placeholder: 'e.g. Adams, Vance', type: 'text' },
];

export const operatorOptions: string[] = [
  'equal to',
  'not equal to',
  'contains',
  'does not contain',
  'starts with',
  'ends with',
  'greater than',
  'less than',
  'is empty',
  'is not empty',
];

export const timezoneOptions: string[] = [
  'America/New_York (EDT)',
  'America/Chicago (CDT)',
  'America/Denver (MDT)',
  'America/Los_Angeles (PDT)',
  'Europe/London (BST/GMT)',
  'Europe/Paris (CEST)',
  'Asia/Kolkata (IST)',
  'Asia/Tokyo (JST)',
  'Australia/Sydney (AEST)',
];
